"""Add UserRequest and ModelLog models

Revision ID: 1ad3935f4f9a
Revises: 
Create Date: 2025-08-03 10:23:12.687437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ad3935f4f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_log_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_details', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_request_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input_text', sa.String(length=500), nullable=False),
    sa.Column('predicted_label', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_request_model')
    op.drop_table('model_log_model')
    # ### end Alembic commands ###
